resource "aws_key_pair" "admin_key" {
  key_name   = "admin_key"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFRrG4CRVanCTZtAgTlebC9j6MPbj20pqANA+c2L7H19UEem+K1zT3xHCpFsIpeYvngTvPe0tkVDgfIXM6mgYpvanJnryi8QQPgbUkjO7UhYSxxb60m7BGMGHCuyEhIFMIShO5bVG0t/+gGFf5yZsNFsAdZjTlh7tRz+cWQTNSMzEah1OuzM2PPJeHpUHqyHZjuSx+2LZWfWz609lGuVwcyQzyqT8drY/pm9RKDY5KTZuIcVrdwSSeYeL00uxgl5gETW5D/d/Ene9pJnC2FlBbu1Dhn+zoowLIz+FlysRTQcSYTnMNLR4LpeMoYzs+TNB3im5ckiw+XwVesQ1I/Z/7 osboxes@osboxes"
}
